name: Auto Vercel Redeploy & Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'   # Every 12 hours

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest deployment ID
        id: get_deployment
        run: |
          DEPLOYMENT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&limit=1" \
            | jq -r '.deployments[0].uid')

          echo "id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

      - name: Trigger new deployment via deploy hook
        run: |
          curl --fail -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"

      - name: Delete previous deployment
        run: |
          curl -X DELETE "https://api.vercel.com/v13/deployments/${{ steps.get_deployment.outputs.id }}" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
